# -*- coding: utf-8 -*-
"""Local C3 agenda contracts for the chat-side companion plugin.

The schedule definition is deliberately imported from ``bot_personal_contract``
so this module cannot drift into a second set of window thresholds.  Everything
stored by this module is a plain JSON-compatible dictionary or scalar.
"""
#
# 以下 import 仅为 re-export：本模块的全部实现已拆到 agenda_contracts_shared.py 与 agenda_contracts_partNN.py，
# 对外 `from .agenda_contracts import X` 的可用名字与拆分前完全一致。
from __future__ import annotations

try:  # package import
    from .agenda_contracts_part01 import (
        _actor_fields,
        _as_date,
        _certainty,
        _enum,
        _evidence_level_mapping,
        _float_confidence,
        _item_datetime,
        _items,
        _list,
        _normalize_participant_roles,
        _normalize_status,
        _now_iso,
        _text,
        _trace,
        _trace_list,
        _version,
        _window_spec,
        derive_temporal_phase,
        interval_overlaps_window,
        normalize_authority_kind,
        normalize_commitment_level,
        normalize_content_granularity,
        normalize_epistemic_status,
        normalize_evidence_kind,
        normalize_evidence_level,
        normalize_fact_eligibility,
        normalize_materialization_state,
        normalize_source_kind,
        normalize_status,
        normalize_temporal_phase,
        normalize_window,
        parse_datetime,
        window_bounds,
        window_for_datetime,
        window_for_minutes,
        window_for_plan_minutes,
    )
except ImportError:  # direct test/import from the plugin directory
    from agenda_contracts_part01 import (
        _actor_fields,
        _as_date,
        _certainty,
        _enum,
        _evidence_level_mapping,
        _float_confidence,
        _item_datetime,
        _items,
        _list,
        _normalize_participant_roles,
        _normalize_status,
        _now_iso,
        _text,
        _trace,
        _trace_list,
        _version,
        _window_spec,
        derive_temporal_phase,
        interval_overlaps_window,
        normalize_authority_kind,
        normalize_commitment_level,
        normalize_content_granularity,
        normalize_epistemic_status,
        normalize_evidence_kind,
        normalize_evidence_level,
        normalize_fact_eligibility,
        normalize_materialization_state,
        normalize_source_kind,
        normalize_status,
        normalize_temporal_phase,
        normalize_window,
        parse_datetime,
        window_bounds,
        window_for_datetime,
        window_for_minutes,
        window_for_plan_minutes,
    )
try:  # package import
    from .agenda_contracts_part02 import (
        agenda_entry_from_activity,
        agenda_entry_from_plan,
        migrate_store,
        normalize_observed_activity,
        normalize_plan_item,
        normalize_reconciliation,
        normalize_window_snapshot,
    )
except ImportError:  # direct test/import from the plugin directory
    from agenda_contracts_part02 import (
        agenda_entry_from_activity,
        agenda_entry_from_plan,
        migrate_store,
        normalize_observed_activity,
        normalize_plan_item,
        normalize_reconciliation,
        normalize_window_snapshot,
    )
try:  # package import
    from .agenda_contracts_shared import (
        ACTOR_TYPES,
        ACTOR_TYPE_VALUES,
        AGENDA_CONTRACT_VERSION,
        AGENDA_SCHEMA_VERSION,
        AGENDA_STATUSES,
        AGENDA_VERSION,
        AUTHORITY_KINDS,
        AUTHORITY_KIND_VALUES,
        AgendaContractError,
        Any,
        BOT_PERSONAL_CANONICAL_SCHEMA_VERSION,
        CANONICAL_FIELDS,
        CANONICAL_SCHEMA_VERSION,
        COMMITMENT_LEVELS,
        COMMITMENT_LEVEL_VALUES,
        CONTENT_GRANULARITIES,
        CONTENT_GRANULARITY_VALUES,
        EPISTEMIC_STATUSES,
        EPISTEMIC_STATUS_VALUES,
        EVIDENCE_KINDS,
        EVIDENCE_KIND_VALUES,
        EVIDENCE_LEVELS,
        FACT_ELIGIBILITIES,
        FACT_ELIGIBILITY_VALUES,
        Iterable,
        MATERIALIZATION_STATES,
        MATERIALIZATION_STATE_VALUES,
        Real,
        RejectedSource,
        SCHEDULE_WINDOWS,
        SOURCE_KINDS,
        STATUS_ALIASES,
        ScheduleAuthorityAdapter,
        TEMPORAL_PHASES,
        TEMPORAL_PHASE_VALUES,
        TrustedScheduleRef,
        VerificationResult,
        WINDOW_SLUGS,
        ZoneInfo,
        _CONTRACT_WINDOWS,
        _CONTRACT_WINDOW_SLUGS,
        _contract_window_for_minutes,
        date,
        datetime,
        deepcopy,
        hashlib,
        json,
        stable_id,
        time,
        timedelta,
        timezone,
        timezone_or_default,
        validate_structured_schedule_ref,
    )
except ImportError:  # direct test/import from the plugin directory
    from agenda_contracts_shared import (
        ACTOR_TYPES,
        ACTOR_TYPE_VALUES,
        AGENDA_CONTRACT_VERSION,
        AGENDA_SCHEMA_VERSION,
        AGENDA_STATUSES,
        AGENDA_VERSION,
        AUTHORITY_KINDS,
        AUTHORITY_KIND_VALUES,
        AgendaContractError,
        Any,
        BOT_PERSONAL_CANONICAL_SCHEMA_VERSION,
        CANONICAL_FIELDS,
        CANONICAL_SCHEMA_VERSION,
        COMMITMENT_LEVELS,
        COMMITMENT_LEVEL_VALUES,
        CONTENT_GRANULARITIES,
        CONTENT_GRANULARITY_VALUES,
        EPISTEMIC_STATUSES,
        EPISTEMIC_STATUS_VALUES,
        EVIDENCE_KINDS,
        EVIDENCE_KIND_VALUES,
        EVIDENCE_LEVELS,
        FACT_ELIGIBILITIES,
        FACT_ELIGIBILITY_VALUES,
        Iterable,
        MATERIALIZATION_STATES,
        MATERIALIZATION_STATE_VALUES,
        Real,
        RejectedSource,
        SCHEDULE_WINDOWS,
        SOURCE_KINDS,
        STATUS_ALIASES,
        ScheduleAuthorityAdapter,
        TEMPORAL_PHASES,
        TEMPORAL_PHASE_VALUES,
        TrustedScheduleRef,
        VerificationResult,
        WINDOW_SLUGS,
        ZoneInfo,
        _CONTRACT_WINDOWS,
        _CONTRACT_WINDOW_SLUGS,
        _contract_window_for_minutes,
        date,
        datetime,
        deepcopy,
        hashlib,
        json,
        stable_id,
        time,
        timedelta,
        timezone,
        timezone_or_default,
        validate_structured_schedule_ref,
    )
