# -*- coding: utf-8 -*-
from __future__ import annotations
import re

PLUGIN_NAME = "astrbot_plugin_private_companion"
DATA_VERSION = 1

# 关系网持久化与审核入口共享的容量契约。
WORLDBOOK_PENDING_OBSERVATION_CAPACITY = 24
WORLDBOOK_IMPORTANT_MEMORY_CAPACITY = 8

PAGE_THEME_NAMES = frozenset(
    {"classic", "warm", "forest", "sakura", "ocean", "lavender", "ink", "sunset"}
)
PAGE_FONT_NAMES = frozenset(
    {"original", "yahei", "dengxian", "source_han", "simsun", "kaiti", "fangsong", "cheng"}
)

MODEL_PROVIDER_KEYS = frozenset(
    {
        "FAST_RESPONSE_PROVIDER_ID",
        "COMPLEX_REASONING_PROVIDER_ID",
        "CREATIVE_MODEL_PROVIDER_ID",
        "LLM_PROVIDER_ID",
        "MAI_STYLE_PROVIDER_ID",
        "DAILY_PLAN_PROVIDER_ID",
        "DETAIL_ENHANCEMENT_PROVIDER_ID",
        "DREAM_DIARY_PROVIDER_ID",
        "CREATIVE_PROVIDER_ID",
        "CREATIVE_OUTLINE_PROVIDER_ID",
        "CREATIVE_REVIEW_PROVIDER_ID",
        "VOICE_PROMPT_PROVIDER_ID",
        "tts_conversion_provider_id",
        "PHOTO_PROMPT_PROVIDER_ID",
        "NARRATION_PROVIDER_ID",
        "HISTORY_SUMMARY_PROVIDER_ID",
        "RESPONSE_REVIEW_PROVIDER_ID",
        "SMART_SILENCE_PROVIDER_ID",
        "PROACTIVE_PERSONA_JUDGE_PROVIDER_ID",
        "TROUBLESHOOTING_PROVIDER_ID",
        "DAILY_REVIEW_PROVIDER_ID",
        "SMART_MESSAGE_DEBOUNCE_PROVIDER_ID",
        "REST_WAKEUP_PROVIDER_ID",
        "RELATIONSHIP_ANALYSIS_PROVIDER_ID",
        "EMOTION_JUDGEMENT_PROVIDER_ID",
        "COMPANION_MEMORY_PROVIDER_ID",
        "DIALOGUE_EPISODE_PROVIDER_ID",
        "GROUP_INTERJECT_PROVIDER_ID",
        "GROUP_EPISODE_PROVIDER_ID",
        "GROUP_SLANG_PROVIDER_ID",
        "GROUP_FOLLOWUP_JUDGE_PROVIDER_ID",
        "FORWARD_MESSAGE_PROVIDER_ID",
        "PLUGIN_VISION_PROVIDER_ID",
        "READING_ARCHIVE_VISION_PROVIDER_ID",
        "REACTION_EXPRESSION_EMBEDDING_PROVIDER_ID",
        "NEWS_PROVIDER_ID",
        "WEB_EXPLORATION_PROVIDER_ID",
    }
)

MODEL_TASK_PROVIDER_KEYS = {
    "daily_plan": "DAILY_PLAN_PROVIDER_ID",
    "detail": "DETAIL_ENHANCEMENT_PROVIDER_ID",
    "full_test_detail": "DETAIL_ENHANCEMENT_PROVIDER_ID",
    "dream": "DREAM_DIARY_PROVIDER_ID",
    "diary": "DREAM_DIARY_PROVIDER_ID",
    "diary_rewrite": "DREAM_DIARY_PROVIDER_ID",
    "diary_derivatives": "DREAM_DIARY_PROVIDER_ID",
    "bookshelf_password": "DREAM_DIARY_PROVIDER_ID",
    "bookshelf_password_reason": "DREAM_DIARY_PROVIDER_ID",
    "creative_project": "CREATIVE_PROVIDER_ID",
    "creative_writing": "CREATIVE_PROVIDER_ID",
    "creative_outline": "CREATIVE_OUTLINE_PROVIDER_ID",
    "creative_review": "CREATIVE_REVIEW_PROVIDER_ID",
    "creative_extract": "CREATIVE_REVIEW_PROVIDER_ID",
    "voice": "VOICE_PROMPT_PROVIDER_ID",
    "voice_repair": "VOICE_PROMPT_PROVIDER_ID",
    "tts_visible_translation": "tts_conversion_provider_id",
    "tts_postprocess": "tts_conversion_provider_id",
    "tts_conversion": "tts_conversion_provider_id",
    "tts_spoken_conversion": "tts_conversion_provider_id",
    "photo_prompt": "PHOTO_PROMPT_PROVIDER_ID",
    "natural_photo_ack_rewrite": "PHOTO_PROMPT_PROVIDER_ID",
    "natural_photo_done_rewrite": "PHOTO_PROMPT_PROVIDER_ID",
    "screen_narration": "NARRATION_PROVIDER_ID",
    "private_image_only_framework": "NARRATION_PROVIDER_ID",
    "private_image_only_fallback": "NARRATION_PROVIDER_ID",
    "yesterday_summary": "HISTORY_SUMMARY_PROVIDER_ID",
    "response_review": "RESPONSE_REVIEW_PROVIDER_ID",
    "proactive_send_review": "RESPONSE_REVIEW_PROVIDER_ID",
    "proactive_reference_rewrite": "RESPONSE_REVIEW_PROVIDER_ID",
    "proactive_message_fallback": "RESPONSE_REVIEW_PROVIDER_ID",
    "group_question_wakeup_reply_review": "RESPONSE_REVIEW_PROVIDER_ID",
    "group_air_reply_guard": "RESPONSE_REVIEW_PROVIDER_ID",
    "smart_silence": "SMART_SILENCE_PROVIDER_ID",
    "proactive_persona_judge": "PROACTIVE_PERSONA_JUDGE_PROVIDER_ID",
    "companion_manual_diagnosis": "TROUBLESHOOTING_PROVIDER_ID",
    "troubleshooting_model_diagnostics": "TROUBLESHOOTING_PROVIDER_ID",
    "daily_review": "DAILY_REVIEW_PROVIDER_ID",
    "smart_message_debounce": "SMART_MESSAGE_DEBOUNCE_PROVIDER_ID",
    "rest_wakeup_judge": "REST_WAKEUP_PROVIDER_ID",
    "relationship": "RELATIONSHIP_ANALYSIS_PROVIDER_ID",
    "worldbook_registration": "RELATIONSHIP_ANALYSIS_PROVIDER_ID",
    "emotion_judgement": "EMOTION_JUDGEMENT_PROVIDER_ID",
    "memory_profile": "COMPANION_MEMORY_PROVIDER_ID",
    "dialogue_episode": "DIALOGUE_EPISODE_PROVIDER_ID",
    "group_interject": "GROUP_INTERJECT_PROVIDER_ID",
    "group_episode": "GROUP_EPISODE_PROVIDER_ID",
    "group_slang": "GROUP_SLANG_PROVIDER_ID",
    "group_followup_judge": "GROUP_FOLLOWUP_JUDGE_PROVIDER_ID",
    "forward_message": "FORWARD_MESSAGE_PROVIDER_ID",
    "forward_message_image_vision": "PLUGIN_VISION_PROVIDER_ID",
    "private_image_vision": "PLUGIN_VISION_PROVIDER_ID",
    "group_nsfw_image_review": "PLUGIN_VISION_PROVIDER_ID",
    "reading_archive_vision": "READING_ARCHIVE_VISION_PROVIDER_ID",
    "news_digest": "NEWS_PROVIDER_ID",
    "external_event_self_link": "NEWS_PROVIDER_ID",
    "web_exploration_query": "WEB_EXPLORATION_PROVIDER_ID",
    "web_exploration_digest": "WEB_EXPLORATION_PROVIDER_ID",
    "atrelay_rewrite": "MAI_STYLE_PROVIDER_ID",
    "atrelay_receipt_rewrite": "MAI_STYLE_PROVIDER_ID",
}

MODEL_TASK_PROVIDER_PREFIXES = (
    ("qzone_", "MAI_STYLE_PROVIDER_ID"),
    ("persona_", "COMPLEX_REASONING_PROVIDER_ID"),
    ("roleplay_", "COMPLEX_REASONING_PROVIDER_ID"),
)

MODEL_QUICK_TIMEOUT_KEYS = {
    "LLM_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "MAI_STYLE_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "DAILY_PLAN_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "DETAIL_ENHANCEMENT_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "DREAM_DIARY_PROVIDER_ID": "CREATIVE_MODEL_PROVIDER_ID",
    "CREATIVE_PROVIDER_ID": "CREATIVE_MODEL_PROVIDER_ID",
    "CREATIVE_OUTLINE_PROVIDER_ID": "CREATIVE_MODEL_PROVIDER_ID",
    "CREATIVE_REVIEW_PROVIDER_ID": "CREATIVE_MODEL_PROVIDER_ID",
    "VOICE_PROMPT_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "tts_conversion_provider_id": "FAST_RESPONSE_PROVIDER_ID",
    "PHOTO_PROMPT_PROVIDER_ID": "CREATIVE_MODEL_PROVIDER_ID",
    "NARRATION_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "HISTORY_SUMMARY_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "RESPONSE_REVIEW_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "SMART_SILENCE_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "PROACTIVE_PERSONA_JUDGE_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "TROUBLESHOOTING_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "DAILY_REVIEW_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "SMART_MESSAGE_DEBOUNCE_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "REST_WAKEUP_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "RELATIONSHIP_ANALYSIS_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "EMOTION_JUDGEMENT_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "COMPANION_MEMORY_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "DIALOGUE_EPISODE_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "GROUP_INTERJECT_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "GROUP_EPISODE_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "GROUP_SLANG_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "GROUP_FOLLOWUP_JUDGE_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "FORWARD_MESSAGE_PROVIDER_ID": "COMPLEX_REASONING_PROVIDER_ID",
    "PLUGIN_VISION_PROVIDER_ID": "PLUGIN_VISION_PROVIDER_ID",
    # 资料归档视觉模型在快速模式下也保持独立，不能复用通用识图的超时配置。
    "READING_ARCHIVE_VISION_PROVIDER_ID": "READING_ARCHIVE_VISION_PROVIDER_ID",
    "NEWS_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
    "WEB_EXPLORATION_PROVIDER_ID": "FAST_RESPONSE_PROVIDER_ID",
}

DEFAULT_REPLY_STYLE_PROMPT = (
    "每次回复至多三句话；简单的回答尽可能保持在 1~2 句，并尽可能保持口语化与简洁化。"
    "回复长度和语气应该与当前对话节奏相匹配，必须使用简体中文进行回复，话语符合社交媒体交流习惯。"
    "当你需要解决复杂问题或进行详细说明时，可以无视这一要求。"
)

DEFAULT_NATURAL_LANGUAGE_PHOTO_EXTRA_PROMPT = "clean clear image, natural composition, no unrelated text, no watermark, no logo, no explanatory panels"

# 日常计划文案 - 生活化JK口语
DEFAULT_DAILY_PLAN_ITEMS = [
    {"time": "08:20", "activity": "起床收拾", "mood": "开心", "message_seed": "新的一天开始啦——该起床咯~"},
    {"time": "09:10", "activity": "整理今天的小事", "mood": "平稳", "message_seed": "先把今天的事情理清楚～"},
    {"time": "10:20", "activity": "专心做正事啦", "mood": "专注", "message_seed": "认真干活咯"},
    {"time": "12:15", "activity": "干饭+午休时间", "mood": "开心", "message_seed": "干饭人干饭魂！不许饿肚子～"},
    {"time": "14:10", "activity": "下午继续努力", "mood": "专注", "message_seed": "下午也要加油呀"},
    {"time": "16:40", "activity": "摸鱼休息一下下", "mood": "慵懒", "message_seed": "歇会儿啦，别太累咯"},
    {"time": "18:10", "activity": "收工放松啦", "mood": "放松", "message_seed": "可算能休息会了"},
    {"time": "21:40", "activity": "准备睡觉觉", "mood": "安静", "message_seed": "要乖乖准备休息咯～"},
]

# 状态描述 - 软萌口语化
DEFAULT_HUMANIZED_STATE = {
    "date": "",
    "sleep": "昨晚睡得超香！",
    "dream": "不记得做什么梦啦",
    "health": "身体状态超棒哦",
    "hunger": "不饿也不撑刚刚好",
    "body_cycle": "身体没什么不舒服",
    "location": "在熟悉的小地方待着",
    "weather": "天气看起来还不错",
    "mood_bias": "心情超平和～",
    "energy": 70,
    "note": "今天状态超好，开开心心过一天啦",
}

# 语音兜底文案 - 自然不生硬
VOICE_FALLBACK_TEMPLATES = [
    "喂喂～在不在呀",
    "喂喂喂",
    "别光顾着忙，记得休息哦",
    "懒得打字啦，直接跟你说咯",
]

TIMER_TAG_PATTERN = re.compile(r"<timer>\s*(.*?)\s*</timer>", re.IGNORECASE | re.DOTALL)
SUPPORTED_TIMER_FORMATS = (
    "%Y-%m-%d-%H:%M:%S",
    "%Y-%m-%d %H:%M:%S",
    "%Y/%m/%d %H:%M:%S",
    "%Y-%m-%d-%H:%M",
    "%Y-%m-%d %H:%M",
    "%Y/%m/%d %H:%M",
)

_DATA_STORE_KEYS = (
    "users",
    "daily_plan",
    "daily_plan_history",
    "agenda_version",
    "observed_activities",
    "window_snapshots",
    "agenda_reconciliation_history",
    "daily_state",
    "state_conditions",
    "state_generated_day",
    "bot_diaries",
    "dream_fragments",
    "diary_generated_day",
    "recent_photo_generations",
    "recent_photo_continuity",
    "photo_generation_scope_attempts",
    "photo_reference_feedback",
    "daily_story_plan",
    "detail_enhanced_day",
    "detail_enhanced_segments",
    "schedule_adjustments",
    "yesterday_conversation_summary",
    "can_do",
    "important_dates",
    "memo_notes",
    "qq_presence_state",
    "creative_projects",
    "creative_memory_pool",
    "proactive_candidate_pool",
    "external_proactive_abilities",
    "boundary_feedback_reports",
    "boundary_feedback_vent_history",
    "worldbook_entries",
    "worldbook_member_profiles",
    "worldbook_group_profiles",
    "photo_reference_assets",
    "worldbook_import_state",
    "atrelay_send_log",
    "inbound_debounce_stats",
    "group_llm_reply_blocks",
    "reaction_expression_group_states",
    "balance_awareness",
    "qweather_location",
    "weather_alerts",
    "weather_alert_awareness",
    "body_monitor_integration",
    "environment_change_awareness",
    "personal_goal_state",
    "food_menu",
    "daily_review_reports",
    "daily_review_active_guidance",
    "daily_review_last_attempt",
    "daily_review_completed_day",
    "daily_review_case_audit",
    "bot_personal_outbox",
)

# 触发原因 - 真人化表达
_REASON_TEXT = {
    "morning_greeting": "早上跟你说早安",
    "noon_greeting": "午间问候",
    "evening_greeting": "晚上跟{name}道晚安",
    "check_in": "关心一下{name}的状态",
    "activity_followup": "在{name}忙完后问一句",
    "open_loop_followup": "自然接起和{name}之前没聊完的那件事",
    "anonymous_area_dwell": "离开后想起{name}刚才在外面待了挺久",
    "anonymous_area_familiarity": "模糊地觉得{name}最近似乎有个常去的地方",
    "quiet_care": "安静地问候一下",
    "memory_echo": "想起和{name}上次聊过的一件小事",
    "mood_checkin": "惦记{name}昨天提过的情绪状态",
    "absence_miss": "隔了几天没聊，有一点想念{name}",
    "activity_share": "跟{name}分享小日常",
    "diary_share": "跟{name}说说今天的小事",
    "state_share": "说说当前状态",
    "important_date_share": "提醒{name}重要的日子",
    "special_day_greeting": "在特别的日子里第一时间问候{name}",
    "memo_note_reminder": "提醒{name}一张到期便签",
    "birthday_curiosity": "好奇地问问{name}的生日",
    "birthday_celebration": "给{name}送上一份生日小惊喜",
    "birthday_eve_hint": "在生日前夜留一点轻轻的期待",
    "birthday_makeup": "补上一句生日祝福",
    "birthday_afterglow": "接住生日之后的一点余温",
    "background_schedule": "提一句当前日程",
    "insomnia_night": "睡不着，想跟{name}说说话",
    "goodnight_screen_check": "互道晚安后轻声提醒{name}早点休息",
    "post_goodnight_group_activity": "互道晚安后发现{name}还在群里活跃",
    "group_share": "跟{name}分享群里的有趣片段",
    "bili_video_share": "跟{name}分享一个 B 站视频",
    "news_share": "跟{name}分享刚看到的一条新闻",
    "web_exploration_share": "跟{name}分享刚探索到的新发现",
    "creative_share": "跟{name}分享小说片段",
    "reading_archive_share": "提起漫画资料",
    "reading_archive_recommendation_request": "向{name}问问有没有适合的阅读推荐",
    "game_invite": "想约{name}再玩一局",
    "dream_share": "跟{name}分享刚想起的一段梦",
    "qzone_life_publish": "把一点生活片段分享给{name}",
    "low_balance": "发现自己的零花钱有点不够用了",
    "health_alert": "注意到一项值得温和关心的身体状态变化",
    "environment_change": "注意到外面的环境突然变了",
    "weather_alert": "收到一条与当前位置有关的气象预警",
    "personal_goal_progress": "自己的一个长期目标有了新进展",
    "meal_care": "惦记{name}有没有按时吃东西",
    "meal_care_followup": "还想把刚才那顿饭问清楚一点",
}

# 动作描述 - 生活化
_ACTION_TEXT = {
    "message": "主动留了一句话",
    "screen_peek": "看了眼本机屏幕",
    "photo_text": "分享了一张照片",
    "poke": "戳了一下",
    "voice": "用语音说了一句",
    "reading_archive_read": "私下翻了会儿漫画资料",
}

# 主动能力注册表 - 给提示词和调试输出共用
PROACTIVE_ABILITY_REGISTRY = [
    {
        "module": "主动消息",
        "name": "message",
        "label": "文字私聊",
        "when": "没有明确媒介契机,或只需要很轻地接一句话",
        "use_for": "早安、午间问候、轻关心、顺手分享、承接用户上一句",
        "avoid": "把生活状态写成汇报,或为了发消息硬编动作",
    },
    {
        "module": "主动行为",
        "name": "screen_peek",
        "label": "轻窥屏",
        "when": "仅主要用户/本机屏幕授权场景下,想确认主要用户电脑前是否还在忙",
        "use_for": "主要用户 check_in、quiet_care、短空档里的本机屏幕试探",
        "avoid": "用于次要用户或非本机对象、复述屏幕内容、承认偷看、把观察写成分析报告",
    },
    {
        "module": "主动行为",
        "name": "photo_text",
        "label": "图片加一句话",
        "when": "当前场景里有任何适合顺手拍给熟人的具体画面",
        "use_for": "activity_share、diary_share、午间或傍晚的小分享；具体主体由模型按上下文选择,不要只用于天气",
        "avoid": "说图在生成、图好了、还在队列里,或解释生成流程",
    },
    {
        "module": "主动行为",
        "name": "voice",
        "label": "短语音",
        "when": "不想打长字、夜里想轻一点、或关系足够近时留一句短声",
        "use_for": "quiet_care、evening_greeting、insomnia_night、很短的贴近感",
        "avoid": "描述自己发语音的过程,或让语音像正式播报",
    },
    {
        "module": "主动行为",
        "name": "poke",
        "label": "戳一戳",
        "when": "很熟、很短、偏玩笑的触碰感,通常只做前置动作",
        "use_for": "轻提醒、半撒娇的试探、名字开场后的补一下",
        "avoid": "连续戳、报数、解释为什么戳",
    },
    {
        "module": "主动行为",
        "name": "reading_archive_read",
        "label": "私下翻资料",
        "when": "检测到 Reading Archive II,且 Bot 空闲、无聊或夜里自己找点东西看",
        "use_for": "内部阅读、低频形成读后印象,必要时很含蓄地提一句",
        "avoid": "主动发送文件、露骨复述内容、把搜索/插件/视觉模型过程说出来",
    },
]

# 模拟事件 - 软萌内心想法
_SIMULATION_FALLBACK_EVENTS = [
    {
        "reason": "morning_greeting",
        "action": "message",
        "why": "一醒来就想跟你打招呼",
        "topic": "早安啦",
        "scene": "刚起床的时候",
        "tone": "软软的",
        "impulse": "第一时间就想找你啦",
    },
    {
        "reason": "activity_share",
        "action": "message",
        "why": "日常里碰到一点有意思的事，想短短提一句",
        "topic": "日常小事",
        "scene": "闲下来时",
        "tone": "轻快",
        "impulse": "想把刚碰到的小事顺口提一下",
    },
    {
        "reason": "evening_greeting",
        "action": "message",
        "why": "准备睡觉前，想轻轻说声晚安",
        "topic": "睡前晚安",
        "scene": "准备休息的时候",
        "tone": "安静",
        "impulse": "想在睡前和用户说声晚安",
    },
]

# 默认用户模板（无文本，无需修改）
_DEFAULT_USER_TEMPLATE = {
    "enabled": True,
    "auto_enabled": False,
    "auto_profile_created": False,
    "auto_profile_created_at": 0,
    "profile_origin": "",
    "relationship_role": "",
    "relationship_mode": "normal",
    "relationship_ledger": [],
    "relationship_daily_totals": {},
    "relationship_last_effective_at": 0,
    "relationship_decay_settled_day": "",
    "relationship_last_decay_stage_drop_at": 0,
    "current_interaction": {},
    "emotion_event_ledger": [],
    "last_emotion_event": {},
    "proactive_daily_limit": -1,
    "proactive_idle_minutes": -1,
    "proactive_min_interval_minutes": -1,
    "photo_daily_limit": -1,
    "screen_peek_daily_limit": -1,
    "poke_daily_limit": -1,
    "proactive_boundary_note": "",
    "nickname": "",
    "style": "",
    "umo": "",
    "last_seen": 0,
    "last_activity_at": 0,
    "last_sent": 0,
    "sent_day": "",
    "sent_today": 0,
    "ignored_streak": 0,
    "last_user_message": "",
    "last_user_message_at": 0,
    "last_inbound_gap_seconds": 0,
    "last_inbound_gap_observed_at": 0,
    "last_reunion_ack_at": 0,
    "last_companion_message": "",
    "last_companion_message_at": 0,
    "goodnight_screen_check_due_at": 0,
    "goodnight_screen_check_episode_at": 0,
    "goodnight_screen_check_episode_key": "",
    "goodnight_screen_check_checked_at": 0,
    "goodnight_screen_check_checked_episode_key": "",
    "goodnight_screen_check_state": "",
    "last_proactive_reason": "",
    "last_proactive_action": "",
    "last_proactive_behavior_summary": "",
    "last_proactive_motive": "",
    "last_proactive_sent_at": 0,
    "last_proactive_source": "",
    "chronotype_profile": {},
    "proactive_source_feedback": {},
    "planned_proactive_burst": False,
    "proactive_burst_index": 0,
    "proactive_burst_origin_id": "",
    "recent_proactive_topics": [],
    "memory_echo_context": {},
    "last_memory_echo_key": "",
    "last_memory_echo_at": 0,
    "memory_echo_checked_key": "",
    "mood_checkin_context": {},
    "last_mood_checkin_key": "",
    "last_mood_checkin_at": 0,
    "mood_checkin_checked_key": "",
    "absence_miss_context": {},
    "last_absence_miss_key": "",
    "last_absence_miss_at": 0,
    "absence_miss_checked_key": "",
    "game_invite_context": {},
    "last_game_invite_key": "",
    "last_game_invite_at": 0,
    "game_invite_checked_key": "",
    "pending_followup_event": {},
    "suspended_proactive": {},
    "simulation_mode": {},
    "inbound_count": 0,
    "proactive_sent_count": 0,
    "reply_count": 0,
    "action_reply_affinity": {},
    "relationship_score": 0,
    "req041_relationship_source_revision": 0,
    "companion_memory": {},
    "expression_profile": {},
    "intent_profile": {},
    "reaction_expression": {},
    "recent_reply_topics": [],
    "postprocess_stats": {},
    "dialogue_episodes": [],
    "open_loops": [],
    "memory_corrections": [],
    "bot_self_preferences": [],
    "conversation_departure": {},
    "conversation_departure_offer_at": 0,
    "action_preferences": {},
    "action_consequences": [],
    "state_continuity": {},
    "episode_message_count": 0,
    "last_episode_refresh_at": 0,
    "last_memory_refresh_at": 0,
    "awaiting_reply_since": 0,
    "last_reply_at": 0,
    "private_inbound_count": 0,
    "next_proactive_at": 0,
    "last_proactive_skip_at": 0,
    "last_proactive_skip_reason": "",
    "last_proactive_skip_prefix": "",
    "proactive_impulses": [],
    "recent_proactive_hesitations": [],
    "last_proactive_hesitation_at": 0,
    "last_proactive_hesitation_note": "",
    "proactive_afterglow": {},
    "recent_proactive_afterglows": [],
    "planned_proactive_reason": "",
    "planned_proactive_action": "",
    "planned_proactive_motive": "",
    "planned_proactive_topic": "",
    "planned_proactive_source": "",
    "planned_proactive_kind": "",
    "planned_proactive_route_version": 0,
    "planned_proactive_route_dedupe_key": "",
    "planned_proactive_route_review_profile": "",
    "planned_proactive_route_retry_profile": "",
    "planned_proactive_route_cancel_if_new_inbound": True,
    "planned_proactive_route_recent_chat_policy": "",
    "planned_proactive_route_allow_automatic_followup": False,
    "planned_proactive_route_disable_segmenting": False,
    "planned_proactive_response_expectation": "",
    "planned_proactive_origin_event_id": "",
    "planned_proactive_route_preflight_action": "",
    "planned_proactive_route_preflight_note": "",
    "planned_proactive_impulse_id": "",
    "planned_proactive_window_start_at": 0,
    "planned_proactive_best_until_at": 0,
    "planned_proactive_expire_at": 0,
    "planned_proactive_origin_at": 0,
    "planned_proactive_origin_key": "",
    "planned_proactive_freshness": "",
    "planned_proactive_delivery_state": "",
    "planned_proactive_trigger_message_id": "",
    "planned_proactive_trigger_umo": "",
    "planned_proactive_trigger_ts": 0,
    "planned_proactive_trigger_inbound_count": -1,
    "planned_proactive_semantic_kind": "",
    "planned_proactive_anchor_type": "",
    "planned_proactive_semantic_score": 0,
    "planned_proactive_semantic_note": "",
    "planned_proactive_model_judge_signature": "",
    "planned_proactive_model_judge_result": {},
    "planned_proactive_model_judge_at": 0,
    "planned_candidate_id": "",
    "planned_event_chain": [],
    "planned_opener_mode": "",
    "planned_followup_kind": "",
    "planned_proactive_quota_exempt": False,
    "last_proactive_kind": "",
    "proactive_route_sent_counts": {},
    "group_share_context": {},
    "last_group_share_key": "",
    "last_group_share_at": 0,
    "last_group_share_snapshot": {},
    "bilibili_video_context": {},
    "last_bilibili_share_key": "",
    "last_bilibili_share_at": 0,
    "creative_share_context": {},
    "last_creative_share_key": "",
    "last_creative_share_at": 0,
    "last_creative_share_snapshot": {},
    "poke_echo_suppress_until": 0,
    "poke_action_inflight_until": 0,
    "last_poke_action_at": 0,
    "llm_timer_event": {},
    "greeting_sent_day": "",
    "greetings_sent": [],
    "greetings_suppressed_by_inbound": [],
    "morning_greeting_sent_at": 0,
    "morning_greeting_reply_at": 0,
    "proactive_daypart_counts": {},
    "proactive_daypart_day": "",
    "photo_sent_today": 0,
    "photo_sent_day": "",
    "photo_generated_today": 0,
    "photo_generated_day": "",
    "screen_peek_today": 0,
    "screen_peek_day": "",
    "screen_peek_last_at": 0,
    "last_unanswered_screen_peek_at": 0,
    "meal_care_day": "",
    "meal_care_asked": [],
    "meal_care_satisfied": [],
    "meal_check_context": {},
    "planned_meal_care_context": {},
}

_DEFAULT_GROUP_TEMPLATE = {
    "enabled": True,
    "group_id": "",
    "manual_group_name": "",
    "message_count": 0,
    "last_seen": 0,
    "last_interject_at": 0,
    "interject_day": "",
    "interject_today": 0,
    "recent_messages": [],
    "recent_bot_replies": [],
    "members": {},
    "role_snapshot": {},
    "member_safety": {},
    "slang_terms": [],
    "slang_meanings": {},
    "topic_signatures": [],
    "topic_threads": [],
    "group_episodes": [],
    "relationship_edges": {},
    "interjection_feedback": {},
    "last_bot_interjection": {},
    "repeat_follow_state": {},
    "pending_atrelay_tasks": [],
    "last_speaker": {},
    "active_bot_conversation": {},
    "atmosphere": {},
    "last_summary_at": 0,
    "last_episode_refresh_at": 0,
    "last_slang_summary_at": 0,
}

# ---------- 创作系统数据结构 ----------

CREATIVE_STORY_BIBLE_TEMPLATE = {
    "mainline_direction": "",
    "active_themes": [],
    "resolved_threads": [],
    "unresolved_threads": [],
    "important_facts": [],
    "next_direction": "",
    # 故事内时间锚点（如"初秋的傍晚"），用于防止连续片段时间倒流或原地打转。
    "story_time": "",
    "recent_keywords": [],
    "recent_outlines": [],
    "last_updated_chunk": 0,
}

CREATIVE_MEMORY_MAX_ENTRIES = 50
CREATIVE_SIMILARITY_THRESHOLD = 0.72
CREATIVE_SIMILARITY_RETRIES = 2
CREATIVE_REVIEW_MIN_SCORE = 7
CREATIVE_MAX_REVISION_HISTORY = 10
CREATIVE_FALLBACK_CHUNKS = [
    "角色把那句话写到一半,忽然停住。窗外的声音很轻,像有人把另一个世界折起来,塞进了玻璃杯底。",
    "角色把那个念头又往后推了一小步,像把一枚很轻的纸片压进书页里,等下次再翻开。",
    "笔尖在纸上停了一秒,又继续往下走。风从窗缝里挤进来,翻动了桌角的便签。",
    "角色忽然想到一个画面,远处的灯塔在雾里一闪一闪,像在给谁打暗号。",
    "这段话写了又删,删了又写。最后角色叹了口气,把手机屏幕朝下扣在桌上。",
]

# Kept only so startup cleanup can remove fallback text written by older versions.
CREATIVE_LEGACY_FALLBACK_CHUNKS = [
    "她把那句话写到一半,忽然停住。窗外的声音很轻,像有人把另一个世界折起来,塞进了玻璃杯底。",
    "她把那个念头又往后推了一小步,像把一枚很轻的纸片压进书页里,等下次再翻开。",
    "她忽然想到一个画面,远处的灯塔在雾里一闪一闪,像在给谁打暗号。",
    "这段话写了又删,删了又写。最后她叹了口气,把手机屏幕朝下扣在桌上。",
]

DEFAULT_CREATIVE_PROJECT_TEMPLATE = {
    "id": "",
    "title": "",
    "work_type": "短篇小说",
    "premise": "",
    "tone": "",
    "point_of_view": "第三人称有限视角",
    "source": "life",
    "source_text": "",
    "target_chars": 2000,
    "current_chars": 0,
    "status": "drafting",
    "draft_chunks": [],
    "disclosed_milestones": [],
    "story_bible": {},
    "creative_memory_pool": [],
    "outline": [],
    "characters": [],
    "revision_notes": [],
    "quality_reviews": [],
    "manual_edits": [],
    "last_manual_edit_at": 0,
    "last_manual_edit_summary": "",
    "writing_provider_id": "",
    "review_provider_id": "",
    "next_hint": "",
    "created_at": 0,
    "last_advanced_at": 0,
    "next_advance_at": 0,
    "last_share_at": 0,
    "share_count": 0,
}

DEFAULT_CREATIVE_CHARACTER_TEMPLATE = {
    "id": "",
    "name": "",
    "role": "",
    "description": "",
    "appearance": "",
    "personality": "",
    "background": "",
    "relationships": [],
    "must_keep_traits": [],
    "status": "alive",
    "created_at": 0,
    "updated_at": 0,
}

DEFAULT_CREATIVE_REVIEW_TEMPLATE = {
    "id": "",
    "chunk_index": -1,
    "scores": {
        "persona": 0,
        "progress": 0,
        "repetition": 0,
        "continuity": 0,
        "coherence": 0,
    },
    "overall": 0,
    "issues": [],
    "suggestions": [],
    "provider_id": "",
    "created_at": 0,
}
