"""Typed prompt authoring and rendering for Private Companion."""

from __future__ import annotations

import copy
import hashlib
import json
import re
import string
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from enum import Enum
from typing import Any
from types import MappingProxyType
from xml.sax.saxutils import escape
try:  # package import
    from .conversation_prompt_section_part01 import (
        ExactText,
        PhotoPromptContent,
        PromptCData,
        PromptDocument,
        PromptDocumentPart,
        PromptField,
        PromptGroup,
        PromptHeadingRef,
        PromptLabel,
        PromptLabelStyle,
        PromptList,
        PromptRenderMode,
        PromptRenderSpec,
        PromptSection,
        PromptTemplate,
        PromptText,
        XmlElement,
        _MISSING,
        _validate_prompt_content,
        _validate_prompt_identity,
        _validate_prompt_title,
        _validate_xml_name,
        exact_text,
        prompt_cdata,
        prompt_field,
        prompt_group,
        prompt_heading_ref,
        prompt_list,
        prompt_text,
    )
except ImportError:  # direct test/import from the plugin directory
    from conversation_prompt_section_part01 import (
        ExactText,
        PhotoPromptContent,
        PromptCData,
        PromptDocument,
        PromptDocumentPart,
        PromptField,
        PromptGroup,
        PromptHeadingRef,
        PromptLabel,
        PromptLabelStyle,
        PromptList,
        PromptRenderMode,
        PromptRenderSpec,
        PromptSection,
        PromptTemplate,
        PromptText,
        XmlElement,
        _MISSING,
        _validate_prompt_content,
        _validate_prompt_identity,
        _validate_prompt_title,
        _validate_xml_name,
        exact_text,
        prompt_cdata,
        prompt_field,
        prompt_group,
        prompt_heading_ref,
        prompt_list,
        prompt_text,
    )
try:  # package import
    from .conversation_prompt_section_part02 import (
        _cdata_text,
        _coerce_render_mode,
        _fingerprint_content,
        _fingerprint_scalar,
        _fingerprint_section_payload,
        _has_content,
        _list_item_tag,
        _plain_content,
        _render_body_only,
        _render_body_section,
        _render_conversation_xml,
        _render_exact,
        _render_labeled,
        _render_labeled_section,
        _render_photo_prompt,
        _render_xml_child,
        _render_xml_content,
        _render_xml_element,
        _render_xml_section,
        _render_xml_value,
        _section_has_content,
        _xml_attribute,
        _xml_string,
        _xml_text,
        prompt_document,
        prompt_document_part,
        prompt_section,
        prompt_section_fingerprint,
        xml_element,
    )
except ImportError:  # direct test/import from the plugin directory
    from conversation_prompt_section_part02 import (
        _cdata_text,
        _coerce_render_mode,
        _fingerprint_content,
        _fingerprint_scalar,
        _fingerprint_section_payload,
        _has_content,
        _list_item_tag,
        _plain_content,
        _render_body_only,
        _render_body_section,
        _render_conversation_xml,
        _render_exact,
        _render_labeled,
        _render_labeled_section,
        _render_photo_prompt,
        _render_xml_child,
        _render_xml_content,
        _render_xml_element,
        _render_xml_section,
        _render_xml_value,
        _section_has_content,
        _xml_attribute,
        _xml_string,
        _xml_text,
        prompt_document,
        prompt_document_part,
        prompt_section,
        prompt_section_fingerprint,
        xml_element,
    )
try:  # package import
    from .conversation_prompt_section_part03 import (
        _render_prompt_document_channel,
        _render_prompt_label,
        render_prompt_content,
        render_prompt_document,
        render_prompt_sections,
    )
except ImportError:  # direct test/import from the plugin directory
    from conversation_prompt_section_part03 import (
        _render_prompt_document_channel,
        _render_prompt_label,
        render_prompt_content,
        render_prompt_document,
        render_prompt_sections,
    )


__all__ = [
    "ExactText",
    "PromptCData",
    "PromptDocument",
    "PromptDocumentPart",
    "PromptField",
    "PromptGroup",
    "PromptHeadingRef",
    "PromptLabel",
    "PromptLabelStyle",
    "PromptList",
    "PhotoPromptContent",
    "PromptRenderMode",
    "PromptRenderSpec",
    "PromptSection",
    "PromptTemplate",
    "PromptText",
    "XmlElement",
    "exact_text",
    "prompt_cdata",
    "prompt_document",
    "prompt_document_part",
    "prompt_field",
    "prompt_group",
    "prompt_heading_ref",
    "prompt_list",
    "prompt_section",
    "prompt_section_fingerprint",
    "prompt_text",
    "render_prompt_document",
    "render_prompt_content",
    "render_prompt_sections",
    "xml_element",
]
