# -*- coding: utf-8 -*-
"""PrivateCompanionPageApiConfigPart03Mixin。

由 tools/split_mixin_domain.py 从 page_api_config.py 机械抽取（1 个方法 + 0 个模块级名字 + 0 个类级赋值 / 752 行）。
方法体零改动：所有 self.xxx 依赖通过继承链解析（宿主类 PrivateCompanionPageApiConfigMixin）。
"""
from __future__ import annotations

from .page_api_config_shared import CYCLE_SETTING_KEYS, PAGE_PRIVATE_CONFIG_KEYS, logger
from .page_api_config_shared import Any
from .page_api_config_shared import CatalogValidationError
from .page_api_config_shared import deepcopy
from .page_api_config_shared import runtime_persona_setting
from .page_api_config_shared import validate_and_serialize



class PrivateCompanionPageApiConfigPart03Mixin:
    """PrivateCompanionPageApiConfigPart03Mixin（从 PrivateCompanionPageApiConfigMixin 拆出）。"""


    def _runtime_settings(self) -> dict[str, Any]:
        keys = [
            "bot_name",
            "page_font_family",
            "page_theme",
            "provider_config_mode",
            "model_timeout_overrides",
            "background_llm_request_max_attempts",
            "model_request_max_attempts_overrides",
            "model_token_limit_overrides",
            "model_fallback_overrides",
            "model_replacement_scope",
            "model_replacement_rules",
            "enable_sensitive_model_replacement",
            "sensitive_replacement_keywords",
            "enable_deepseek_peak_replacement",
            "enable_llm_streaming",
            "enable_body_monitor_integration",
            "deepseek_peak_windows",
            "deepseek_peak_timezone",
            "deepseek_peak_match_keywords",
            "plugin_specific_persona_id",
            "enable_multi_persona_mode",
            "multi_persona_ids",
            "target_user_ids",
            "private_user_aliases",
            "private_user_delivery_aliases",
            "target_platform",
            "require_private_opt_in",
            "environment_perception_timezone",
            "holiday_country",
            "enable_environment_perception",
            "enable_balance_awareness",
            "enable_holiday_perception",
            "enable_platform_perception",
            "enable_model_perception",
            "enable_worldview_perception",
            "enable_lunar_perception",
            "enable_solar_term_perception",
            "enable_almanac_perception",
            "default_nickname",
            "enable_auto_user_profile_creation",
            "portrait_global_mode",
            "auto_profile_platforms",
            "default_nickname_strategy",
            "default_proactive_enabled",
            "default_proactive_daily_limit",
            "default_interaction_band",
            "enable_custom_relationship_stage_policy",
            "relationship_stage_policy",
            "relationship_positive_stage_cap_key",
            "normal_interaction_band_cap",
            "owner_group_relationship_projection",
            "owner_group_interaction_projection",
            "enable_relationship_content_tiers",
            "enable_flirt_content_tier",
            "owner_exclusive_label",
            "owner_exclusive_tone",
            "owner_exclusive_address_style",
            "owner_exclusive_proactive_limit",
            "enable_group_relationship_affinity",
            "group_relationship_affinity_allowlist",
            "group_relationship_daily_net_cap",
            "group_relationship_window_minutes",
            "group_relationship_window_absolute_cap",
            "group_relationship_person_daily_absolute_cap",
            "group_relationship_scope_daily_absolute_cap",
            "relationship_event_window_minutes",
            "relationship_positive_event_cap",
            "relationship_negative_event_cap",
            "relationship_positive_daily_cap",
            "relationship_decay_grace_days",
            "relationship_decay_early_per_day",
            "relationship_decay_middle_per_day",
            "relationship_decay_late_per_day",
            "default_style",
            "reply_style_prompt",
            "enable_persona_voice_channels",
            "persona_conversation_voice_prompt",
            "persona_creative_voice_prompt",
            "persona_planning_voice_prompt",
            "persona_inner_voice_prompt",
            "persona_proactive_voice_prompt",
            "proactive_prompt_template",
            "proactive_persona_judge_send_threshold",
            "proactive_persona_judge_cache_minutes",
            "proactive_persona_judge_max_daily",
            "schedule_persona_prompt",
            "schedule_worldview_prompt",
            "roleplay_user_profile_prompt",
            "roleplay_knowledge_source_ids",
            "worldview_adaptation_mode",
            "worldview_adaptation_prompt",
            "quiet_hours",
            "passive_injection_position",
            "passive_review_mode",
            "passive_review_strength",
            "proactive_review_mode",
            "smart_silence_judge_mode",
            "smart_silence_min_confidence",
            "smart_silence_model_timeout_seconds",
            "proactive_review_strength",
            "proactive_review_hard_risk_threshold",
            "proactive_review_low_score_threshold",
            "proactive_review_pressure_threshold",
            "response_review_max_chars",
            "passive_topic_memory_hours",
            "tts_synthesis_backend",
            "tts_provider_id_zh",
            "tts_provider_id_ja",
            "tts_provider_id_en",
            "tts_mimo_tool_name",
            "tts_mimo_voice_name",
            "tts_mimo_style_prompt",
            "tts_generation_mode",
            "tts_voice_language",
            "tts_fishaudio_model",
            "tts_fishaudio_emotion_mode",
            "tts_delivery_mode",
            "tts_foreign_text_mode",
            "tts_message_scope",
            "tts_conversion_scope",
            "tts_conversion_provider_id",
            "tts_extra_prompt",
            "tts_trigger_keywords",
            "tts_frequency_control_mode",
            "tts_constraint_mode",
            "tts_session_min_interval_seconds",
            "tts_private_min_interval_seconds",
            "tts_group_min_interval_seconds",
            "tts_trigger_probability",
            "tts_private_trigger_probability",
            "tts_group_trigger_probability",
            "enable_tts_local_playback",
            "enable_tts_local_playback_live_only",
            "enable_tts_live_subtitle_sync",
            "tts_live_subtitle_url",
            "tts_local_playback_volume",
            "tts_local_playback_min_interval_seconds",
            "auto_voice_enabled",
            "auto_voice_full_conversion_enabled",
            "auto_voice_probability",
            "auto_voice_max_chars",
            "auto_voice_cooldown_seconds",
            "main_user_voice_probability",
            "main_user_mention_voice_keywords",
            "main_user_mention_voice_probability",
            "main_user_mention_voice_prompt",
            "daily_token_limit",
            "enable_daily_token_soft_limit",
            "daily_token_soft_limit",
            "humanized_state_intensity",
            "enable_health_state",
            "enable_hunger_state",
            *CYCLE_SETTING_KEYS,
            "enable_rest_reply_simulation",
            "rest_reply_mode",
            "rest_reply_probability",
            "rest_reply_llm_threshold",
            "rest_reply_active_windows",
            "rest_reply_awake_grace_minutes",
            "enable_rest_backlog_reply",
            "rest_backlog_max_messages",
            "REST_WAKEUP_PROVIDER_ID",
            "enable_busy_reply_gate",
            "busy_reply_min_delay_seconds",
            "busy_reply_max_delay_seconds",
            "busy_reply_proactive_resume_buffer_minutes",
            "check_interval_seconds",
            "proactive_intensity_preset",
            "idle_minutes",
            "min_interval_minutes",
            "proactive_unanswered_slowdown_start",
            "proactive_unanswered_max_interval_multiplier",
            "friend_unanswered_max_cooldown_hours",
            "max_daily_messages",
            "proactive_photo_text_probability",
            "inbound_message_debounce_seconds",
            "enable_message_debounce",
            "enable_smart_message_debounce",
            "SMART_MESSAGE_DEBOUNCE_PROVIDER_ID",
            "smart_message_debounce_model_timeout_seconds",
            "smart_message_debounce_wait_seconds",
            "smart_message_debounce_learning_window_seconds",
            "smart_message_debounce_examples_limit",
            "enable_recall_enhancement",
            "enable_recall_cancel_reply",
            "enable_recall_message_cache",
            "enable_recall_transcribe_command",
            "enable_forbidden_word_recall",
            "recall_forbidden_words",
            "recall_forbidden_scope",
            "recall_forbidden_word_case_sensitive",
            "text_message_debounce_seconds",
            "image_message_debounce_seconds",
            "forward_message_debounce_seconds",
            "text_message_debounce_max_wait_seconds",
            "message_debounce_max_merge_messages",
            "enable_semantic_message_debounce",
            "semantic_message_debounce_seconds",
            "enable_proactive_quote_trigger_message",
            "enable_quote_group_reply",
            "enable_quote_group_interjection",
            "enable_quote_private_proactive",
            "quote_skip_short_reply_chars",
            "quote_target_strategy",
            "enable_photo_text_action",
            "enable_user_requested_photo_generation",
            "allow_generate_photo_on_reaction_turns",
            "enable_photo_reference_image",
            "photo_action_max_daily",
            "enable_generated_photo_cleanup",
            "generated_photo_retention_days",
            "generated_photo_max_mb",
            "photo_generation_backend",
            "custom_photo_tool_name",
            "custom_photo_tool_prompt_param",
            "custom_photo_tool_kind_param",
            "custom_photo_tool_reference_param",
            "custom_photo_tool_extra_params",
            "COMFYUI_TEXT2IMG_WORKFLOW_NAME",
            "COMFYUI_SELFIE_WORKFLOW_NAME",
            "photo_reference_catalog",
            "photo_persona_reference_image_path",
            "photo_reference_library",
            "enable_wardrobe",
            "wardrobe_tendency",
            "enable_wardrobe_prompt",
            "wardrobe_prompt_max_items",
            "wardrobe_image_max_count",
            "wardrobe_image_prompt",
            "WARDROBE_VISION_PROVIDER_ID",
            "wardrobe_outfit_mode",
            "wardrobe_injection_detail",
            "wardrobe_outfit_rotation_days",
            "enable_wardrobe_outfit_generate",
            "WARDROBE_OUTFIT_PROVIDER_ID",
            "wardrobe_items",
            "wardrobe_outfits",
            "wardrobe_photo_source",
            "enable_daily_outfit_photo",
            "enable_creative_cover_generation",
            "daily_outfit_photo_prompt",
            "daily_outfit_rotation_days",
            "enable_natural_language_photo_generation",
            "natural_language_photo_generation_mode",
            "command_photo_generation_max_daily",
            "natural_language_photo_generation_max_daily",
            "natural_language_photo_extra_prompt",
            "comfyui_photo_wait_seconds",
            "enable_local_photo_load_guard",
            "local_photo_cpu_busy_percent",
            "local_photo_memory_busy_percent",
            "local_photo_defer_minutes",
            "external_image_api_platform",
            "EXTERNAL_IMAGE_API_BASE_URL",
            "EXTERNAL_IMAGE_API_KEY",
            "EXTERNAL_IMAGE_API_MODEL",
            "external_image_api_size",
            "external_image_api_timeout_seconds",
            "external_image_api_custom_headers",
            "external_image_download_proxy",
            "external_image_download_use_environment_proxy",
            "external_image_api_endpoints",
            "enable_backup_external_image_api",
            "backup_external_image_api_platform",
            "BACKUP_EXTERNAL_IMAGE_API_BASE_URL",
            "BACKUP_EXTERNAL_IMAGE_API_KEY",
            "BACKUP_EXTERNAL_IMAGE_API_MODEL",
            "backup_external_image_api_size",
            "backup_external_image_api_timeout_seconds",
            "backup_external_image_api_custom_headers",
            "photo_generation_prompt_format",
            "photo_generation_style",
            "photo_generation_style_custom_prompt",
            "photo_generation_negative_prompt_mode",
            "photo_generation_negative_prompt",
            "photo_generation_text2img_negative_prompt",
            "photo_generation_selfie_negative_prompt",
            "photo_generation_edit_negative_prompt",
            "photo_generation_fixed_prompt",
            "photo_generation_text2img_fixed_prompt",
            "photo_generation_selfie_fixed_prompt",
            "photo_generation_edit_fixed_prompt",
            "photo_generation_scene_presets",
            "enable_bot_relationship_network",
            "bot_relationship_cards",
            "private_image_vision_wait_seconds",
            "private_image_provider_timeout_seconds",
            "private_image_provider_failure_cooldown_seconds",
            "private_image_vision_provider_priority",
            "private_image_vision_custom_prompt",
            "private_image_vision_max_chars",
            "enable_context_image_captioning",
            "context_image_caption_max_items",
            "context_image_caption_timeout_seconds",
            "enable_private_image_gif_enhancement",
            "private_image_gif_max_frames",
            "enable_private_image_self_recognition",
            "private_image_self_recognition_hint",
            "enable_private_image_vision_cache",
            "private_image_vision_cache_max_items",
            "enable_group_image_understanding",
            "enable_group_image_wakeup",
            "group_image_vision_wait_seconds",
            "group_image_max_images",
            "screen_diary_context_max_chars",
            "enable_segmented_proactive_reply",
            "segmented_proactive_scope",
            "segmented_proactive_chat_scope",
            "enable_segmented_proactive_chat_profiles",
            "segmented_proactive_private_enabled",
            "segmented_proactive_private_scope",
            "segmented_proactive_private_threshold",
            "segmented_proactive_private_min_segment_chars",
            "segmented_proactive_private_max_segments",
            "segmented_proactive_private_send_as_forward",
            "segmented_proactive_private_interval_method",
            "segmented_proactive_private_interval_min",
            "segmented_proactive_private_interval_max",
            "segmented_proactive_private_log_base",
            "segmented_proactive_group_enabled",
            "segmented_proactive_group_scope",
            "segmented_proactive_group_threshold",
            "segmented_proactive_group_min_segment_chars",
            "segmented_proactive_group_max_segments",
            "segmented_proactive_group_send_as_forward",
            "segmented_proactive_group_interval_method",
            "segmented_proactive_group_interval_min",
            "segmented_proactive_group_interval_max",
            "segmented_proactive_group_log_base",
            "segmented_proactive_threshold",
            "segmented_proactive_min_segment_chars",
            "segmented_proactive_max_segments",
            "segmented_proactive_send_as_forward",
            "segmented_proactive_voice_strategy",
            "segmented_proactive_image_strategy",
            "segmented_proactive_at_strategy",
            "segmented_proactive_face_strategy",
            "segmented_proactive_component_order",
            "segmented_proactive_other_strategy",
            "segmented_proactive_split_mode",
            "segmented_proactive_regex",
            "segmented_proactive_split_words",
            "enable_segmented_proactive_content_cleanup",
            "segmented_proactive_content_cleanup_scope",
            "segmented_proactive_content_cleanup_rule",
            "segmented_proactive_content_cleanup_words",
            "enable_segmented_proactive_content_replacement",
            "segmented_proactive_content_replacements",
            "segmented_proactive_interval_method",
            "segmented_proactive_interval_min",
            "segmented_proactive_interval_max",
            "segmented_proactive_log_base",
            "group_conversation_followup_seconds",
            "group_conversation_followup_max_turns",
            "enable_group_conversation_followup",
            "enable_group_repeat_follow",
            "group_repeat_trigger_threshold",
            "group_repeat_count_distinct_users_only",
            "group_interject_min_interval_minutes",
            "group_interject_max_daily",
            "group_repeat_follow_probability",
            "group_repeat_interrupt_probability",
            "group_repeat_interrupt_probability_step",
            "group_repeat_interrupt_text",
            "group_repeat_interrupt_image_path",
            "group_scene_recent_limit",
            "enable_group_history_injection",
            "group_scene_recent_max_chars",
            "enable_group_reality_promise_guard",
            "group_wakeup_direct_words",
            "group_wakeup_owner_direct_words",
            "group_wakeup_context_words",
            "group_wakeup_interest_keywords",
            "group_wakeup_interest_probability",
            "group_wakeup_short_text_wait_seconds",
            "group_wakeup_question_threshold",
            "group_wakeup_cold_group_threshold",
            "group_wakeup_cooldown_seconds",
            "group_wakeup_cold_group_idle_minutes",
            "group_wakeup_generated_keyword_limit",
            "group_wakeup_topic_interest_max_boost",
            "group_wakeup_debounce_pending_penalty",
            "group_wakeup_fatigue_limit",
            "group_wakeup_fatigue_decay_minutes",
            "group_wakeup_log_limit",
            "enable_group_high_intensity_mode",
            "group_high_intensity_wakeup_window_seconds",
            "group_high_intensity_wakeup_threshold",
            "group_high_intensity_cooldown_seconds",
            "group_high_intensity_merge_seconds",
            "group_high_intensity_max_merge_messages",
            "group_high_intensity_merge_scope",
            "enable_forward_message_adaptation",
            "forward_message_mode",
            "forward_message_max_messages",
            "forward_message_max_chars",
            "forward_message_parse_nested",
            "forward_message_image_vision",
            "forward_message_image_limit",
            "enable_recall_cancel_reply",
            "enable_recall_message_cache",
            "enable_recall_transcribe_command",
            "recall_message_cache_ttl_seconds",
            "recall_message_cache_max_items",
            "recall_message_image_cache_max_mb",
            "enable_forbidden_word_recall",
            "recall_forbidden_words",
            "recall_forbidden_scope",
            "recall_forbidden_word_case_sensitive",
            "screen_diary_context_max_chars",
            "max_group_recent_messages",
            "max_group_slang_terms",
            "group_slang_web_search_terms",
            "group_slang_web_search_results",
            "memory_refresh_interval_minutes",
            "episode_memory_refresh_messages",
            "episode_memory_refresh_minutes",
            "max_companion_memory_items",
            "max_learned_expression_items",
            "expression_learning_mode",
            "enable_expression_manual_review",
            "enable_expression_style_review",
            "expression_private_learning_source_mode",
            "expression_private_learning_source_ids",
            "expression_group_learning_source_mode",
            "expression_group_learning_source_ids",
            "expression_group_learning_daily_batch_limit",
            "expression_group_learning_min_new_messages",
            "expression_private_application_mode",
            "expression_private_application_user_ids",
            "expression_group_application_mode",
            "expression_group_application_ids",
            "max_dialogue_episodes",
            "user_habit_min_count",
            "user_habit_max_items",
            "emotional_gate_hurt_threshold",
            "emotional_gate_refuse_threshold",
            "emotional_gate_recovery_per_hour",
            "emotional_gate_max_hurt_minutes",
            "enable_llm_emotion_judgement",
            "emotion_judgement_mode",
            "enable_skill_growth_simulation",
            "skill_growth_rate",
            "skill_growth_custom_skills",
            "enable_skill_growth_passive_injection",
            "enable_skill_growth_schedule_influence",
            "skill_growth_schedule_influence_strength",
            "enable_bilibili_integration",
            "enable_bilibili_boredom_watch",
            "bilibili_boredom_min_interval_hours",
            "bilibili_share_probability",
            "bilibili_share_min_score",
            "enable_news_integration",
            "enable_news_boredom_read",
            "enable_news_daily_hot_read",
            "enable_ai_daily_watch",
            "ai_daily_sources",
            "ai_daily_prefer_text_version",
            "enable_external_event_self_link",
            "news_min_interval_hours",
            "news_share_probability",
            "external_event_self_link_probability",
            "external_event_self_link_cooldown_hours",
            "external_link_share_cooldown_hours",
            "news_max_items_per_source",
            "news_sources",
            "news_hot_sources",
            "news_hot_max_items",
            "enable_web_exploration",
            "enable_web_exploration_boredom_search",
            "web_exploration_min_interval_hours",
            "web_exploration_share_probability",
            "web_exploration_max_results",
            "web_exploration_interests",
            "WEB_EXPLORATION_API_BASE_URL",
            "WEB_EXPLORATION_API_KEY",
            "WEB_EXPLORATION_API_MODEL",
            "enable_qzone_integration",
            "QZONE_COOKIE",
            "enable_qzone_life_publish",
            "qzone_life_publish_min_interval_hours",
            "qzone_life_publish_probability",
            "qzone_life_publish_max_daily",
            "qzone_life_publish_window_mode",
            "qzone_life_publish_windows",
            "qzone_life_publish_allow_insomnia_night",
            "qzone_life_publish_intra_day_gap_minutes",
            "qzone_life_publish_similarity_threshold",
            "qzone_publish_style_prompt",
            "enable_qzone_generated_image_publish",
            "qzone_generated_image_probability",
            "qzone_publish_image_style_prompt",
            "enable_qzone_comment_inbox",
            "qzone_comment_inbox_interval_minutes",
            "qzone_comment_inbox_recent_posts",
            "qzone_comment_inbox_max_replies_per_tick",
            "enable_qzone_emotional_vent_publish",
            "qzone_emotional_vent_threshold",
            "qzone_emotional_vent_cooldown_hours",
            "qzone_emotional_vent_probability",
            "enable_reading_archive_integration",
            "enable_reading_archive_boredom_read",
            "enable_reading_archive_ask_recommendation",
            "enable_reading_archive_vision",
            "enable_reading_archive_page_comments",
            "enable_reading_archive_rating",
            "enable_reading_archive_preference_influence",
            "enable_unanswered_screen_peek_followup",
            "unanswered_screen_peek_after_minutes",
            "unanswered_screen_peek_cooldown_minutes",
            "enable_goodnight_screen_check",
            "goodnight_screen_check_delay_minutes",
            "reading_archive_min_interval_hours",
            "reading_archive_max_photo_count",
            "reading_archive_share_probability",
            "reading_archive_ask_probability",
            "reading_archive_preference_min_ratings",
            "reading_archive_preference_max_terms",
            "reading_archive_default_keywords",
            "reading_archive_blocked_tags",
            "enable_unanswered_screen_peek_followup",
            "unanswered_screen_peek_after_minutes",
            "unanswered_screen_peek_cooldown_minutes",
            "enable_goodnight_screen_check",
            "goodnight_screen_check_delay_minutes",
            "enable_creative_writing",
            "enable_creative_work_read_guard",
            "creative_inspiration_probability",
            "creative_share_probability",
            "creative_chars_per_session",
            "creative_max_active_projects",
            "creative_hidden_mode",
            "creative_direction_prompt",
            "enable_worldbook_member_recognition",
            "worldbook_auto_import",
            "worldbook_member_match_aliases",
            "worldbook_self_registration",
            "worldbook_self_registration_block_words",
            "worldbook_self_registration_block_reply",
            "worldbook_auto_pending_observations",
            "worldbook_member_inject_limit",
            "worldbook_config_paths",
            "cross_user_memory_owner_only",
            "enable_atrelay_tools",
            "atrelay_require_worldbook_first",
            "atrelay_member_cache_minutes",
            "atrelay_sensitive_confirm",
            "enable_atrelay_llm_rewrite",
            "atrelay_default_relay_style",
            "atrelay_multi_target_limit",
        ]
        # Keep cycle settings in the overview even when a long-lived AstrBot
        # process has not rebuilt its schema index after a plugin upgrade.
        # The settings endpoint already accepts this explicit contract; the
        # runtime snapshot must expose the same fields for the panel editor.
        for key in CYCLE_SETTING_KEYS:
            if key not in keys:
                keys.append(key)
        provider_keys = self._schema_provider_keys(public_only=True)
        for key in sorted(self._schema_setting_keys(public_only=True) - PAGE_PRIVATE_CONFIG_KEYS):
            if key not in keys and key not in provider_keys:
                keys.append(key)
        values = {
            key: runtime_persona_setting(
                self.plugin,
                key,
                getattr(self.plugin, key, self._config_get(key)),
            )
            for key in keys
        }
        # This is the persisted primary-persona authority. It must remain
        # stable when the WebUI is viewing a secondary persona; the resolver's
        # active scope is only for persona-scoped settings.
        primary_getter = getattr(self.plugin, "_primary_persona_id", None)
        primary_id = (
            primary_getter()
            if callable(primary_getter)
            else getattr(self.plugin, "plugin_specific_persona_id", "")
        )
        values["plugin_specific_persona_id"] = self._single_line(primary_id, 120)
        values["environment_perception_timezone"] = getattr(
            self.plugin,
            "environment_perception_timezone_setting",
            self._config_get("environment_perception_timezone") or "global",
        )
        values["environment_perception_timezone_effective"] = getattr(
            self.plugin,
            "environment_perception_timezone",
            "Asia/Shanghai",
        )
        if "photo_reference_catalog" in values:
            try:
                values["photo_reference_catalog"] = validate_and_serialize(
                    self._photo_reference_catalog_snapshot(sync_runtime=True),
                    preset_names=self._photo_reference_preset_names(),
                )
            except CatalogValidationError as exc:
                logger.warning(
                    "总览参考图目录序列化失败: %s",
                    self._single_line(exc, 180),
                )
                persisted_catalog = self._config_get_raw("photo_reference_catalog", [])
                values["photo_reference_catalog"] = persisted_catalog if isinstance(persisted_catalog, list) else []
        for key in self._schema_bool_keys():
            if key not in values:
                continue
            persisted = self._config_get_raw(key, None)
            if persisted not in (None, ""):
                values[key] = self._normalize_bool_value(persisted)
        busy_reply_defaults = {
            "enable_busy_reply_gate": False,
            "busy_reply_min_delay_seconds": 60,
            "busy_reply_max_delay_seconds": 300,
            "busy_reply_proactive_resume_buffer_minutes": 10,
        }
        for key, default in busy_reply_defaults.items():
            persisted = self._config_get_raw(key, None)
            if persisted in (None, ""):
                values[key] = default
            elif values.get(key) in (None, ""):
                values[key] = persisted
        segmented_setting_keys = (
            "enable_segmented_proactive_reply",
            "enable_llm_controlled_segmenting",
            "llm_controlled_segmenting_prompt",
            "enable_segmented_plugin_rules",
            "segmented_proactive_scope",
            "segmented_proactive_chat_scope",
            "enable_segmented_proactive_chat_profiles",
            "segmented_proactive_private_enabled",
            "segmented_proactive_private_scope",
            "segmented_proactive_private_threshold",
            "segmented_proactive_private_min_segment_chars",
            "segmented_proactive_private_max_segments",
            "segmented_proactive_private_send_as_forward",
            "segmented_proactive_private_interval_method",
            "segmented_proactive_private_interval_min",
            "segmented_proactive_private_interval_max",
            "segmented_proactive_private_log_base",
            "segmented_proactive_group_enabled",
            "segmented_proactive_group_scope",
            "segmented_proactive_group_threshold",
            "segmented_proactive_group_min_segment_chars",
            "segmented_proactive_group_max_segments",
            "segmented_proactive_group_send_as_forward",
            "segmented_proactive_group_interval_method",
            "segmented_proactive_group_interval_min",
            "segmented_proactive_group_interval_max",
            "segmented_proactive_group_log_base",
            "segmented_proactive_threshold",
            "segmented_proactive_min_segment_chars",
            "segmented_proactive_max_segments",
            "segmented_proactive_send_as_forward",
            "segmented_proactive_voice_strategy",
            "segmented_proactive_image_strategy",
            "segmented_proactive_at_strategy",
            "segmented_proactive_face_strategy",
            "segmented_proactive_component_order",
            "segmented_proactive_other_strategy",
            "segmented_proactive_split_mode",
            "segmented_proactive_regex",
            "segmented_proactive_split_words",
            "enable_segmented_proactive_content_cleanup",
            "segmented_proactive_content_cleanup_scope",
            "segmented_proactive_content_cleanup_rule",
            "segmented_proactive_content_cleanup_words",
            "enable_segmented_proactive_content_replacement",
            "segmented_proactive_content_replacements",
            "segmented_proactive_interval_method",
            "segmented_proactive_interval_min",
            "segmented_proactive_interval_max",
            "segmented_proactive_log_base",
        )
        for key in segmented_setting_keys:
            persisted = self._config_get_raw(key, None)
            if persisted not in (None, ""):
                values[key] = deepcopy(persisted)
        values["private_user_aliases"] = self._private_alias_config_text("private_user_aliases")
        values["private_user_delivery_aliases"] = self._private_alias_config_text("private_user_delivery_aliases")
        values.update(
            {
                "enable_reading_archive_integration": bool(getattr(self.plugin, "enable_reading_archive_integration", False)),
                "enable_reading_archive_boredom_read": bool(getattr(self.plugin, "enable_reading_archive_boredom_read", False)),
                "enable_reading_archive_ask_recommendation": bool(getattr(self.plugin, "enable_reading_archive_ask_recommendation", False)),
                "enable_reading_archive_vision": bool(getattr(self.plugin, "enable_reading_archive_vision", True)),
                "enable_reading_archive_page_comments": bool(getattr(self.plugin, "enable_reading_archive_page_comments", True)),
                "enable_reading_archive_rating": bool(getattr(self.plugin, "enable_reading_archive_rating", True)),
                "enable_reading_archive_preference_influence": bool(getattr(self.plugin, "enable_reading_archive_preference_influence", True)),
                "reading_archive_min_interval_hours": getattr(self.plugin, "reading_archive_min_interval_hours", 18),
                "reading_archive_max_photo_count": getattr(self.plugin, "reading_archive_max_photo_count", 60),
                "reading_archive_share_probability": getattr(self.plugin, "reading_archive_share_probability", 0.18),
                "reading_archive_ask_probability": getattr(self.plugin, "reading_archive_ask_probability", 0.16),
                "reading_archive_preference_min_ratings": getattr(self.plugin, "reading_archive_preference_min_ratings", 5),
                "reading_archive_preference_max_terms": getattr(self.plugin, "reading_archive_preference_max_terms", 8),
                "reading_archive_default_keywords": getattr(self.plugin, "reading_archive_default_keywords", ""),
                "reading_archive_blocked_tags": getattr(self.plugin, "reading_archive_blocked_tags", "連載中,長篇,青年漫"),
                "group_repeat_trigger_threshold": int(getattr(self.plugin, "group_repeat_trigger_threshold", 4) or 4),
                "group_repeat_count_distinct_users_only": bool(getattr(self.plugin, "group_repeat_count_distinct_users_only", False)),
                "group_repeat_follow_probability": int(round(float(getattr(self.plugin, "group_repeat_follow_probability", 0.18) or 0) * 100)),
                "group_repeat_interrupt_probability": int(round(float(getattr(self.plugin, "group_repeat_interrupt_probability", 0.10) or 0) * 100)),
                "group_repeat_interrupt_probability_step": int(round(float(getattr(self.plugin, "group_repeat_interrupt_probability_step", 0.12) or 0) * 100)),
            }
        )
        def _percent_attr(name: str, default: float = 0.0, *, inherit: bool = False) -> int:
            try:
                raw = float(getattr(self.plugin, name, default) or 0.0)
            except (TypeError, ValueError):
                raw = default
            if inherit and raw < 0:
                return -1
            if raw <= 1:
                raw *= 100
            return max(-1 if inherit else 0, min(100, int(round(raw))))

        values.update(
            {
                "tts_trigger_probability": _percent_attr("tts_trigger_probability", 0.25),
                "tts_private_trigger_probability": _percent_attr("tts_private_trigger_probability", -0.01, inherit=True),
                "tts_group_trigger_probability": _percent_attr("tts_group_trigger_probability", -0.01, inherit=True),
                "auto_voice_probability": _percent_attr("auto_voice_probability", 0.25),
                "main_user_voice_probability": _percent_attr("main_user_voice_probability", -0.01, inherit=True),
                "main_user_mention_voice_probability": _percent_attr("main_user_mention_voice_probability", 0.0),
                "rest_reply_probability": _percent_attr("rest_reply_probability", 0.18),
            }
        )
        for key in self._schema_bool_keys():
            if key in values:
                values[key] = self._normalize_bool_value(values[key])
        for key in PAGE_PRIVATE_CONFIG_KEYS:
            values.pop(key, None)
        active_getter = getattr(self.plugin, "_active_persona_scope", None)
        active_persona = str(active_getter() if callable(active_getter) else "").strip()
        primary_getter = getattr(self.plugin, "_primary_persona_id", None)
        primary_persona = str(
            primary_getter()
            if callable(primary_getter)
            else getattr(self.plugin, "plugin_specific_persona_id", "")
        ).strip()
        manifest_getter = getattr(self.plugin, "_persona_scope_manifest", None)
        setting_getter = getattr(self.plugin, "get_persona_setting", None)
        if active_persona and active_persona != primary_persona and callable(manifest_getter) and callable(setting_getter):
            manifest = manifest_getter()
            for key in tuple(values):
                entry = manifest.get(key) if isinstance(manifest, dict) else None
                if isinstance(entry, dict) and entry.get("scope") == "persona":
                    try:
                        values[key] = setting_getter(key, active_persona, values[key])
                    except Exception:
                        pass
        return values
