# -*- coding: utf-8 -*-
from .proactive_engine_candidate_shared import (
    logger,
)
from .proactive_engine_candidate_shared import logger
from .proactive_engine_candidate_score_semantics import ProactiveEngineCandidateScoreSemanticsMixin
from .proactive_engine_candidate_planned_delivery_defer import ProactiveEngineCandidatePlannedDeliveryDeferMixin
from .proactive_engine_candidate_offer_planned_status import ProactiveEngineCandidateOfferPlannedStatusMixin
from .proactive_engine_candidate_materialize_record import ProactiveEngineCandidateMaterializeRecordMixin
from .proactive_engine_candidate_impulse_queue_closing_defer import ProactiveEngineCandidateImpulseQueueClosingDeferMixin
from .proactive_engine_candidate_candidate_pool_impulse_window import ProactiveEngineCandidateCandidatePoolImpulseWindowMixin
class ProactiveEngineCandidateMixin(ProactiveEngineCandidateCandidatePoolImpulseWindowMixin, ProactiveEngineCandidateImpulseQueueClosingDeferMixin, ProactiveEngineCandidateMaterializeRecordMixin, ProactiveEngineCandidateOfferPlannedStatusMixin, ProactiveEngineCandidatePlannedDeliveryDeferMixin, ProactiveEngineCandidateScoreSemanticsMixin):
    """候选池/冲动池域（从 ProactiveEngineMixin 拆出）。"""
