"""Public companion runtime contracts."""

from .injection import (
    ACTION_STATUSES,
    CAPABILITY_KINDS,
    CAPABILITY_STATES,
    PROTOCOL_VERSION,
    ActionRequest,
    ActionResult,
    CapabilityConflictError,
    CapabilityDescriptor,
    CapabilityRegistry,
    CompanionEvent,
    ContextContribution,
    Evidence,
    EXTENSION_STATES,
    ExtensionManifest,
    ExtensionRegistry,
    ExtensionStatus,
    InjectionProtocolError,
    Observation,
    ProactiveCandidate,
    RuntimeScope,
    Scope,
)

__all__ = [
    "ACTION_STATUSES",
    "CAPABILITY_KINDS",
    "CAPABILITY_STATES",
    "PROTOCOL_VERSION",
    "ActionRequest",
    "ActionResult",
    "CapabilityConflictError",
    "CapabilityDescriptor",
    "CapabilityRegistry",
    "CompanionEvent",
    "ContextContribution",
    "Evidence",
    "EXTENSION_STATES",
    "ExtensionManifest",
    "ExtensionRegistry",
    "ExtensionStatus",
    "InjectionProtocolError",
    "Observation",
    "ProactiveCandidate",
    "RuntimeScope",
    "Scope",
]
